sylius_twig_hooks:
    hooks:
        'sylius_admin.security.login.page.content':
            sso:
                template: '@GlEventsSyliusAdminSamlPlugin/Security/login/page/content/form/sso.html.twig'
                priority: -100
